export const eventContent = {
  appTitle: "NRIオフィス探検スタンプラリー",
  brandLabel: "NRI COMPANY TOUR",
  subtitle: "オフィスをまわってスタンプを集めよう！",
  introduction: "NRIのオフィスを探検して、全部のスタンプを集めよう！",
  explorationLabel: "OFFICE EXPLORATION",
  progressLabel: "スタンプの進み具合",
  allStampsCollected: "全部のスタンプがそろったよ！",
  stampCelebrationLabel: "STAMP GET!",
  stampCelebrationTitle: "やったね！スタンプゲット！",
  stampCelebrationNext: "気になる場所を探検してみよう！",
  stampModalClose: "探検を続ける",
  uncollectedLabel: "まだだよ",
  collectedLabel: "ゲット！",
  acquiredAtLabel: "取得日時",
  waitingForScan: "QRコードを見つけて読み取ろう",
  scannerButton: "QRコードを読み取る",
  scannerTitle: "QRコードを読み取る",
  scannerStarting: "カメラを準備しています…",
  scannerActive: "枠の中にQRコードを映してください",
  scannerHint: "QRコード全体と、まわりの白い余白まで枠内に入れてください。",
  scannerUnsupported:
    "この端末ではアプリ内読取に必要なカメラ機能を利用できません。端末の標準カメラでQRコードを読み取ってください。",
  scannerPermissionDenied:
    "カメラの使用が許可されていません。ブラウザーの設定でカメラを許可するか、端末の標準カメラでQRコードを読み取ってください。",
  scannerCameraUnavailable:
    "利用できるカメラが見つかりませんでした。端末の標準カメラでQRコードを読み取ってください。",
  scannerError:
    "カメラを開始できませんでした。端末の標準カメラでQRコードを読み取ってください。",
  scannerClose: "閉じる",
  completeTitle: "スタンプラリークリア！",
  completeMessage: "NRIのオフィス探検、おつかれさまでした！",
  completeCheer: "5つのスタンプがそろったよ！",
  completeModalClose: "スタンプラリーを見る",
  duplicateMessage: "このスタンプはすでに取得しています",
  invalidMessage: "このQRコードはスタンプラリーでは使えないようです",
  resetMessage: "スタンプをすべてリセットしました",
  resetButton: "スタンプをすべてリセット",
  resetConfirm:
    "取得したスタンプをすべて削除します。運営スタッフの動作確認時のみ実行してください。よろしいですか？",
  resetDescription: "運営スタッフ用",
  privacyNote: "この端末にはチェックポイントIDと取得日時だけを保存します。",
  footerLabel: "NRI COMPANY TOUR · OFFICE STAMP RALLY",
} as const;
